http:
  routers:
    traefik:
      rule: "Host(`dashboard.codesefaz.local`)"
      service: "api@internal"
      tls:
        domains:
          - main: "codesefaz.local"
            sans:
              - "*.codesefaz.local"

tls:
  certificates:
    - certFile: "/etc/certs/codesefaz.local+9.pem"
      keyFile: "/etc/certs/codesefaz.local+9-key.pem"
