global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https: # Este entrypoint 'https' corresponde ao 'websecure' usado nas labels dos serviços
    address: ":443"
    # Se quiser um certificado padrão global para este entrypoint, defina aqui:
    # tls:
    #   defaultCertificate:
    #     certFile: "/etc/certs/codesefaz.local+9.pem" # Caminho dentro do contêiner
    #     keyFile: "/etc/certs/codesefaz.local+9-key.pem" # Caminho dentro do contêiner

# ... (restante do static.yml)