[tls]
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/certs/cert.pem"
        keyFile = "/certs/key.pem"
  
  [[tls.certificates]]
    certFile = "/certs/chat4.codesefaz.local.pem"
    keyFile = "/certs/chat4.codesefaz.local-key.pem"

  [[tls.certificates]]
    certFile = "/certs/brow.codesefaz.local.pem"
    keyFile = "/certs/brow.codesefaz.local-key.pem"

  [[tls.certificates]]
    certFile = "/certs/evo.codesefaz.local.pem"
    keyFile = "/certs/evo.codesefaz.local-key.pem"

  [[tls.certificates]]
    certFile = "/certs/workflows.codesefaz.local.pem"
    keyFile = "/certs/workflows.codesefaz.local-key.pem"
  
  
  [[tls.certificates]]
    certFile = "/certs/webhooks.codesefaz.local.pem"
    keyFile = "/certs/webhooks.codesefaz.local-key.pem"