# Arquivo: config/dynamic.yml

# Configuração de roteadores dinâmicos (definidos por arquivo)
http:
  routers:
    dashboard: # Roteador para o dashboard do Traefik
      rule: "Host(`dashboard.codesefaz.local`)" # Domínio que ativará este roteador
      service: "api@internal" # Serviço interno do Traefik (API/Dashboard)
      entrypoints:
        - websecure # Este roteador ouvirá no entrypoint websecure (HTTPS)
      tls: {} # Habilita TLS para este roteador (usará certificado que cubra o domínio na regra Host)

# Configuração de certificados TLS estáticos (carregados de arquivos)
tls:
  certificates:
    - certFile: "/certs/codesefaz.local+9.pem" # <--- Caminho DENTRO do contêiner para seu certificado mkcert
      keyFile: "/certs/codesefaz.local+9-key.pem" # <--- Caminho DENTRO do contêiner para sua chave mkcert

# Você pode adicionar mais roteadores ou middlewares aqui, se precisar defini-los via arquivo em vez de labels Docker.
# Exemplo: Roteador para o Whoami definido por arquivo (em vez de labels)
# http:
#   routers:
#     whoami-by-file:
#       rule: "Host(`whoami-file.codesefaz.local`)"
#       service: "whoami-service" # Nome de um serviço que você definiria aqui também
#       entrypoints:
#         - websecure
#       tls: {}
# services: # Seção de serviços dinâmicos definidos por arquivo
#   whoami-service:
#     loadBalancer:
#       servers:
#         - url: http://<IP_ou_nome_do_servico_whoami_na_rede_swarm>:80