version: "3.7"

services:
  traefik:
    image: traefik:v2.11.24
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    command:
      - "--configFile=/etc/traefik/traefik.yml"

    deploy:
      placement:
        constraints:
          - node.role == manager

      labels:
        - "traefik.enable=true"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Permanece o mesmo # Padrão para Traefik interagir com Docker Swarm
      - "./config/static.yml:/etc/traefik/traefik.yml:ro"
      - "./config/dynamic.yml:/etc/traefik/dynamic.yml:ro" # <<< MONTAR O ARQUIVO DINÂMICO
      - "./certs:/certs:ro" # <<< ADICIONAR

    networks:
      - network_swarm_public # Garanta que este nome corresponde à sua rede overlay
      
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      # Específico para Local: Expor a porta do dashboard do Traefik para acesso fácil (opcional)
      - target: 8080 # <<< ADICIONAR
        published: 8080 # <<< ADICIONAR
        mode: host # <<< ADICIONAR

volumes:
  vol_shared:
    external: true
    name: volume_swarm_shared
  # vol_certificates: # <<< PODE REMOVER SE NÃO USAR MAIS PARA ACME
  #   external: true
  #   name: volume_swarm_certificates

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
    # attachable: true # <<< Útil para debug, pode adicionar se quiser
