version: '3'

services:
  whoami:
    image: containous/whoami
    security_opt:
      - no-new-privileges:true
    labels:
      # Enable this container to be mapped by traefik
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      - "traefik.enable=true"
      # Define the network that should be used
      - "traefik.docker.network=network_swarm_public"
      # URL to reach this container
      - "traefik.http.routers.whoami.rule=Host(`whoami.codesefaz.local`)"
      # Activation of TLS
      - "traefik.http.routers.whoami.tls=true"
      # If port is different than 80, use the following service:
      # - "traefik.http.services.<service_name>.loadbalancer.server.port=<port>"
    networks:
      - network_swarm_public

networks:
  network_swarm_public:
    external: true
