version: "3.7"

services:
  n8n_worker:
    image: n8nio/n8n:1.94.0
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    restart: unless-stopped
    command: worker --concurrency=10 # comando padrão para subir o servidor web
    networks:
      - network_compose_public
    environment:
      
    volumes:
      - ca_certs_volume:/usr/local/share/ca-certificates/:ro
    # Configura o Modo de Deploy da Aplicação
    deploy:
      # O editor será executado no modo de replicação
      mode: replicated
      # Vamos ter apenas uma instância do editor
      replicas: 1
      # Limitação
      resources:
        # Definição dos Limites de Recursos deste Serviço
        limits:
          # Define a quantidade de CPU para o N8N para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para o N8N para evitar travamento do Host
          memory: 1024M
      # Configura o modo de atualização do serviço
      update_config:
        # Configura o paralelismo de atualização
        parallelism: 1
        # Configura o tempo de espera entre as atualizações
        delay: 30s
        # Configura a ação em caso de falha
        order: start-first
        # Configura a ação em caso de falha
        failure_action: rollback

volumes:
  ca_certs_volume:
    name: ca_certs_volume
    external: true

networks:
  network_compose_public:
    name: network_compose_public
    external: true
