version: "3.7"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    restart: unless-stopped
    networks:
      - network_compose_public
    # ports:
    #   # Mapeie a porta 80 do contêiner para uma porta no seu host (ex: 8080)
    #   - "8080:80"
    environment:
      # Credenciais de login para o pgAdmin (NÃO são as credenciais do Postgres)
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com" # Altere para o seu e-mail
      PGADMIN_DEFAULT_PASSWORD: "rQhNep96o8Ha5oAxmuTq" # Altere para uma senha forte
      
      # configuração de certificado
      NODE_EXTRA_CA_CERTS: "/usr/local/share/ca-certificates/rootCA.pem"
    volumes:
      # Para persistir as configurações e bancos de dados registrados no pgAdmin
      - pgadmin_data:/var/lib/pgadmin
      - ca_certs_volume:/usr/local/share/ca-certificates/:ro
    labels:
      # --- Configurações Traefik para pgadmin ---
      - "traefik.enable=true" # Habilita o Traefik para este serviço
      - "traefik.docker.network=network_compose_public" # Traefik deve se comunicar nesta rede
      
      # Define o dominio do pgadmin
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOCKER_BASE_URL}`)"
      # Define o tipo de entrada do pgadmin para HTTPS
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      # Define o certificado do pgadmin
      - "traefik.http.routers.pgadmin.tls=true" # Habilita TLS para este roteador

      # Define o nome do serviço no traefik
      - traefik.http.routers.pgadmin.service=pgadmin
      # Define a porta do pgadmin
      - traefik.http.services.pgadmin.loadbalancer.server.port=80

volumes:
  pgadmin_data:
    name: pgadmin_data
  ca_certs_volume:
    name: ca_certs_volume
    external: true

networks:
  network_compose_public:
    name: network_compose_public
    external: true